### PR TITLE
Gigcentral kate

### PR DESCRIPTION
**Pull request by mandyfoster**
Here are the files I am attempting to merge, 1 is deleted, 2 had modifications, and the rest are new files

### CODE REVIEW

**Comment by bschwartz757** [comment]
How do we update our local repos, should we just fetch the entire remote
repository again?

Thanks!
Blake

- Blake Schwartz

**Comment by mandyfoster** [comment]
If you have the local instance of gig central (the master branch), you
should be able to use git checkout <branch name>

**Comment by mandyfoster** [comment]
When you get the branch, I think you can use git diff to get the actual
ones that are different

**Comment by bschwartz757** [comment]
Git checkout origin/master? I guess we can just refer to the latest video
set as he deals with checking out remote branches. Thanks Mandy!!

**Comment by BrettSpencer** [comment]
I think that's what you have to do unless you have a gulp or grunt build
set up.

**Pull request closed without merging**
